// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagementDotNet8Angular17MaterialTailwindAPI.Entities;

public partial class Subject
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<StudentSubject> StudentSubject { get; set; } = new List<StudentSubject>();
}